### ISSUE TITLE
Protocol docs

### ISSUE THREAD

**Issue by slifin** [jpmonettas/flow-storm-debugger#14]
This is less an issue more of a question (let me know if there's a better place to ask):

For the WIP docs here:
https://github.com/jpmonettas/flow-storm-debugger/blob/master/docs/protocol.md

In the three types of messages:
  - :flow-storm/init-trace
  - :flow-storm/add-trace
  - :flow-storm/add-bind-trace

What does it mean to add-bind-trace?

**Comment by jpmonettas** [comment]
Yeah everything is WIP there, I'll complete those documents when I have some time.

:flow-storm/add-bind-trace is for tracing that a value has been bound to a symbol. It is used for lets, fn parameters etc.

You can see some examples here https://github.com/jpmonettas/flow-storm/blob/master/test/flow_storm/all_test.cljc#L43
