### ISSUE TITLE
Clear all tabs

### ISSUE THREAD

**Issue by ingesolvoll** [jpmonettas/flow-storm-debugger#16]
Sometimes the number of tabs can get a bit out of hand. It would be nice to be able to press one button to close all tabs in one go.

**Comment by jpmonettas** [comment]
Have you tried adding a `#ztrace` instead of a `#trace` to the "first form of the flow".

https://github.com/jpmonettas/flow-storm-debugger#working-at-the-repl

With that the flow will always have flow-id=0, it will only generate one tab, and replace it every time you run your code again.

**Comment by ingesolvoll** [comment]
Oh, didn't know that, that's useful!

There are still cases where you would want to not do that, I think. I have a case where a `#trace` is hit a number of times, let's say 5, and I need to inspect more than one of them. Then I run the test 2  or 3 times more, forgetting to clean up. This is the point where closing all those tabs becomes painful, and I often just choose to close the debugger and restart.

**Comment by jpmonettas** [comment]
Yeah I agree that being able to close all tabs is a nice feature to have.

I'm planning to add keyboard support pretty soon and we can add something like hitting `x` clears all flows to start with.

**Comment by jpmonettas** [comment]
This is implemented in 0.3.7, please see https://github.com/jpmonettas/flow-storm-debugger#keyboard-commands
