### ISSUE TITLE
Cannot require in cljs repl

### ISSUE THREAD

**Issue by Reefersleep** [jpmonettas/flow-storm-debugger#17]
I couldn't get `flow-storm-debugger` to work with my main cljs project. 

To simplify things, I tried reproducing it with a bare-bones project.

This was created with `lein new figwheel-main krager --reagent`. 
I've done nothing to it but add `flow-storm-debugger` to the dependency vector.
https://github.com/Reefersleep/krager

On calling `(require '[flow-storm.api :as fsa])` in the repl, I get
```
cljs.user=> (require '[flow-storm.api :as fsa])
Could not Analyze: Not supported: class clojure.core$print  
```
Following that, `fsa` is not a valid reference.

**Comment by jpmonettas** [comment]
I was able to reproduce the issue. First time I see that error message, but also first time I'm trying without shadow-cljs to be honest.

I'll try to figure out what is going on.

Thanks for reporting @Reefersleep !

**Comment by jpmonettas** [comment]
@Reefersleep just figured out that it happens only when you try to require from the repl. Requiring it from the ns macro works fine:

```clojure
(ns ^:figwheel-hooks krager.core
  (:require
   [goog.dom :as gdom]
   [flow-storm.api :as fsa]))
```
You can then :

```
lein fig:build

cljs.user=> (in-ns 'krager.core)
krager.core=> (fsa/connect)
krager.core=> #trace (+ 1 2)

```
So it is maybe an artifact of how fighwheel load files from the repl, no idea.

Let me know if it works for you.

**Comment by jpmonettas** [comment]
Closing this for now, please reopen if the solution doesn't work.
