### ISSUE TITLE
Start the debugger inside the same process as the REPL?

### ISSUE THREAD

**Issue by didibus** [jpmonettas/flow-storm-debugger#18]
Hi,

I'm wondering if there is a way where I don't need a separate process for the debugger? I'd like to start a command line REPL that automatically starts the debugger, so I could straight up write some code in the REPL and trace it to be debugged?

Is there a way to do that?

**Comment by jpmonettas** [comment]
Hi, 

Starting the debugger in the same jvm process should be possible, since it is just a Clojure function.
The traces are currently being reported through a web socket, this is so it works for ClojureScript also, but implement something that skip web sockets when everything is in the same process isn't hard.

I'm not sure what are the benefits of running everything in the same process. Can you expand the idea a little more?

**Comment by didibus** [comment]
Sometimes I start a repl to play around with something, and it be nice if the debugger was started along with it, so if I need it, it is just there for me to use.

**Comment by jpmonettas** [comment]
This should start everything in the same process :

Start a repl with both the debugger and the tracing library loaded :

```bash
clj -Sdeps '{:deps {jpmonettas/flow-storm-debugger {:mvn/version "0.5.0"} jpmonettas/flow-storm {:mvn/version "0.4.2"}}}'
```

```clojure
;; require both
(require '[flow-storm-debugger.main :as fsd])
(require '[flow-storm.api :as fsa])

;; start the debugger in a different thread so you can keep using the repl
(.start (Thread. (fn [] (fsd/-main))))

;; connect the repl to the debugger
(fsa/connect)

;; Start tracing
#trace (+ 1 1)
```

If there is a way of automating the setup in one command it should be possible.

**Comment by jpmonettas** [comment]
@didibus this should do everything in one command :

```bash
clj -Sdeps '{:deps {jpmonettas/flow-storm-debugger {:mvn/version "0.5.0"} jpmonettas/flow-storm {:mvn/version "0.4.2"}}}' \
-e "(require '[flow-storm-debugger.main :as fsd]) (require '[flow-storm.api :as fsa]) (.start (Thread. (fn [] (fsd/-main)))) (fsa/connect) " -r
```
