### ISSUE TITLE
Extract macroexpand to its own lib

### ISSUE THREAD

**Issue by Cyrik** [jpmonettas/flow-storm-debugger#20]
Would you mind if i pulled out your macroexpand code into its own thing?

**Comment by jpmonettas** [comment]
@Cyrik  you mean the `macroexpand-all` defined here https://github.com/jpmonettas/flow-storm/blob/master/src/flow_storm/instrument.clj#L81 ?

Sure, I event forked that from clojure-emacs/orchard https://github.com/clojure-emacs/orchard/blob/master/src/orchard/meta.clj#L313 I don't remember if I modified anything.

**Comment by Cyrik** [comment]
yeah that + the cljs specific fixes. i didn't see a license in the project, so I didn't want to just assume that its fine

**Comment by Cyrik** [comment]
its done in [https://github.com/Cyrik/cljs-macroexpand](https://github.com/Cyrik/cljs-macroexpand)
