### ISSUE TITLE
Any plans for osx dark mode?

### ISSUE THREAD

**Issue by Liverm0r** [jpmonettas/flow-storm-debugger#22]
Would be great to apply system dart-mode automatically.

**Comment by jpmonettas** [comment]
@Liverm0r sorry I'm not sure what is that about, can you please elaborate?

If you mean a dark theme, there are plans. 
What you can do if you want to play around with colors is to overwrite the current styles by passing a :styles keyword to `fs-api/local-connect` or `fs-api/cli-run` like this : 

```clojure
(fs-api/local-connect {:styles "/home/jmonetta/.flow-storm/my-styles.css"})
```
This are the styles you will be overwriting : https://github.com/jpmonettas/flow-storm-debugger/blob/master/resources/styles.css

You can play with changing colors, font sizes, etc. I'm not sure if it is enough to make a dark theme yet.

**Comment by Liverm0r** [comment]
> apply system dart-mode automatically

When I change system dart mode 
![image](https://user-images.githubusercontent.com/14236531/168064560-1f2dc487-11ae-4c84-bc1c-b252ed3cfc98.png)

some apps (slack, obsidian, finder) will automatically recolor themself.

**Comment by jpmonettas** [comment]
Oh you mean Dark mode, I got confused because of Dart the language which Clojure can now compile to.

That looks like a macos specific thing and I'm not aware of any JavaFx feature that allows you to provide a dark theme for the OS.

What I have in mind for a dark theme is to provide a flag that will choose a dark theme stylesheet, but nothing automagical.

**Comment by Liverm0r** [comment]
I have a hack for my vim config about something similar. It's not automagic, but at least it works when I open new vim instance. Here is the code:
```fennel
(let [(ok? msg) (pcall vim.fn.system "defaults read -g AppleInterfaceStyle")]
  (if (string.find msg "Dark")
    (do 
      (set nvim.o.background "dark")
      (vim.api.nvim_command "colorscheme nightfox"))
    (do 
      (set nvim.o.background "light")
      (vim.api.nvim_command "colorscheme dayfox"))))
```
and terminal output:
```bash 
# m1 @ air in ~ [14:47:47] 
$ defaults read -g AppleInterfaceStyle
Dark

# m1 @ air in ~ [14:47:48] 
$ wtheme

# m1 @ air in ~ [14:47:52] 
$ defaults read -g AppleInterfaceStyle
2022-05-12 14:47:54.799 defaults[91028:3974300] 
The domain/default pair of (kCFPreferencesAnyApplication, AppleInterfaceStyle) does not exist
```

But I am not sure if it should be supported. May be flag is ok.

**Comment by jpmonettas** [comment]
Oh, thanks for that script. I think at first I'll just implement a flag but good to know a way to do it, doesn't look too complicated.

**Comment by Liverm0r** [comment]
And there are javafx-ways https://stackoverflow.com/a/65805346/5360247

**Comment by Liverm0r** [comment]
If you don't have mac, I could help testing

**Comment by jpmonettas** [comment]
Great! Thanks @Liverm0r

**Comment by Liverm0r** [comment]
Would you like me to make a pr with this?
