### ISSUE TITLE
Any plans for hotkeys?

### ISSUE THREAD

**Issue by Liverm0r** [jpmonettas/flow-storm-debugger#23]
I would propose a minimal support for:
- changing focus between areas with `tab/shift+tab`;
- changing focus inside area with arrow kes.

**Comment by jpmonettas** [comment]
Yeah, there are plans for keyboard support. 
I'm closing this one since there is a issue for this already https://github.com/jpmonettas/flow-storm-debugger/issues/5
Thanks!

**Comment by Liverm0r** [comment]
oh, I'm sorry, I searched for it but somehow didn see it :(
