### ISSUE TITLE
Closing the debugging session

### ISSUE THREAD

**Issue by danielsz** [jpmonettas/flow-storm-debugger#29]
First things first: thank you for the impressive work! Quite an achievement.

I am integrating this tool in my workflow, and while starting everything with `local-connect` is great, I was wondering how I can close everything with one command. This would allow me to toggle the debugger on and off at the REPL when I need it.  
 
Thank you!

**Comment by jpmonettas** [comment]
Glad you find it useful @danielsz !

There isn't currently any command for working with the debugger like a component system, but should be pretty straight forward to add it.

Currently you can just close the window, and call `(local-connect)` any time you need it again.

There is already `flow-storm.tracer/stop-trace-sender` that will kill the trace sender thread and also `flow-storm.debugger.ui.state-vars/stage` on which you can call `(.close stage)`.

I'll add a function to correctly shutdown the debugger and make sure  it doesn't leak anything. 

Will use this issue to track it.

**Comment by jpmonettas** [comment]
@danielsz The entire debugger (GUI part) uses mount to handle state now. I'm not a fan of mount but going sierra components now will require too many changes, maybe in the future I'll revisit it.

Anyway, if you start the debugger with `flow-storm.api/local-connect` calling `flow-storm.api/stop` will shutdown everything gracefully. Same applies for ClojureScript if you started with  `flow-storm.api/remote-connect`

Cheers!
