### ISSUE TITLE
be able to close or re-order thread tabs

### ISSUE THREAD

**Issue by marcfontaine-dev** [jpmonettas/flow-storm-debugger#36]
When multiple thread tabs are open, it would be great to be able close some of them, or re-order them.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/68030190/182454320-d0548667-52db-42b0-9974-6882a6150ec4.png">

**Comment by jpmonettas** [comment]
Yeah that gets annoying when debugging multithreaded code. I wander if there is a better way :thinking: .

Closing tabs is not hard to implement, but you still have to figure out where is the stuff you are interested in and close the others.

@marcfontaine-dev can you explain a little more about your use case?

**Comment by marcfontaine-dev** [comment]
Couple scenarios, 
1. Running the same web app code multiple times and looking at the differences, if I could group the "meaningful" thread tabs together it would be easier to switch between them. Being able to close the non-relevant tabs would achieve the same result.  
2. Business process that uses a thread pool which spawns up a lot of tabs

**Comment by jpmonettas** [comment]
Ok [this commit](https://github.com/jpmonettas/flow-storm-debugger/commit/6d5ed31df71b2f57576c027bf2e3bd23e95b97db) adds support for closing and reordering thread tabs.

**Comment by marcfontaine-dev** [comment]
Thanks @jpmonettas,
I just tried it and it works great, exactly what I needed.
