### ISSUE TITLE
Get rid of reflection

### ISSUE THREAD

**Issue by Liverm0r** [jpmonettas/flow-storm-debugger#41]
With a  `*warn-on-reflection*` turned on, there would be a list of warnings after running  `(fs-api/local-connect)`. 

```clj
; (err) Reflection warning, flow_storm/debugger/ui/utils.clj:58:9 - call to method addAll on javafx.collections.ObservableList can't be resolved (argument types: unknown).
; (err) Reflection warning, flow_storm/debugger/ui/utils.clj:74:7 - call to method updateItem can't be resolved (target class is unknown).
; (err) Reflection warning, flow_storm/debugger/ui/utils.clj:76:9 - call to method setGraphic on javafx.scene.Node can't be resolved (no such method).
; (err) Reflection warning, flow_storm/debugger/ui/utils.clj:80:9 - reference to field getStyleClass can't be resolved.
....
```

Also, performance would be better without reflection and it would be easier to make native builds with graalvm (if you would ever want to).

Described above is not a big deal, but easy to fix. 
I could make a PR if you'd like to.

**Comment by jpmonettas** [comment]
Hi, thanks for reporting this.
I'm following the recommendations here https://clojure.org/reference/java_interop#typehints where it says ` Normally, one should avoid the use of type hints until there is a known performance bottleneck.` so not trying to get rid of all reflections warnings, just the ones that are called many times and can affect performance.

https://github.com/jpmonettas/flow-storm-debugger/commit/375795018f7cfad27da79194217024809d892766 add more in that utils file that are think are important
