### ISSUE TITLE
Remote debugger can't take :host argument

### ISSUE THREAD

**Issue by FongHou** [jpmonettas/flow-storm-debugger#43]
Hi, thanks for the awesome tool!

I try to connect remote debugger like this, and get a Unreadable arg: "172.24.37.202" error message.

`clj -X:lib/flow-storm flow-storm.debugger.main/start-debugger :host 172.24.37.202 :port 9000`

Though user guide doesn't say :host arg, but start-debugger doc string says it's available. Not sure I use it correctly or not.

I'm sure the nrepl server works because `lein repl :connect 172.24.37.202:9000` works fine.

**Comment by jpmonettas** [comment]
Hi @FongHou! Thanks.

For the clj cli you need to quote strings args like : 

clj -X:lib/flow-storm flow-storm.debugger.main/start-debugger :host '"172.24.37.202"' :port 9000

if you are on a mac or linux shell.

There is some double quoting (double quotes wrapped in single quotes) going on there, look at this for more info https://clojure.org/reference/deps_and_cli#quoting

**Comment by FongHou** [comment]
Thanks @jpmonettas for quick response. Yep, that error is due to tricky edn reader in windows powershell. Now I'm getting a different error. I'm trying to get remote debugger working between windows host (remote debugger UI) and WLS (nrepl server in a terminal). The problem is that WLS can't connect via localhost back to windows host port. Hence, I'm getting errors on WSL side of nrepl console

```
Connection with ws://localhost:7722/ws closed. code=-1 reson=Connection refused remote?=false
Connection with ws://localhost:7722/ws closed. code=-1 reson=Connection refused remote?=false
WebSocket error connection ws://localhost:7722/ws
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:568)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:473)
        at flow_storm.remote_websocket_client.proxy$org.java_websocket.client.WebSocketClient$ff19274a.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

On windows host side, remote debugger WebSocket keep getting timeouts then restarted. 

```
[Starting WebSocket subsystem]
WebSocket server started, listening on 7722
No process connected.
Timeout waiting for sync-remote-api-request response
[WATCHDOG] websocket looks down, trying to reconnect ...
[Stopping WebSocket subsystem]
WebSocket server stopped
[Starting WebSocket subsystem]
WebSocket server started, listening on 7722
No process connected.
Timeout waiting for sync-remote-api-request response
[WATCHDOG] websocket looks down, trying to reconnect ...
[Stopping WebSocket subsystem]
WebSocket server stopped
[Starting WebSocket subsystem]
WebSocket server started, listening on 7722
```

Is there a parameter for remote debugger's websocket bind to an host IP (ie. not localhost/127.0.0.01)

Thanks!

**Comment by jpmonettas** [comment]
Oh that is a bug for sure, I haven't been trying remote connections (apart from ClojureScript locally) lately. I'll have to create a extra parameter so you can specify your own ip for the runtime to be able to establish the websocket back to the debugger.

Until that you should be able to connect the websocket by hand. On the Clojure process you need to :
```clojure
(require '[flow-storm.api :as fsa])
(fsa/remote-connect {:host "192.168.1.10"})
```

You can leave that on your main (while developing) so it happens every time your app starts or do it over a repl.

Does it make sense?

**Comment by FongHou** [comment]
There seems some kind of race condition prevent it from working. I still get previous errors rolling in my consoles. 

When I tried to eval (fsa/remote-connect), I got no error but #rtrace run failed.


```
; eval (root-form): (fsa/remote-connect {:host "192.168.0.48"})
Remote Clojure runtime initialized
nil
; --------------------------------------------------------------------------------
; State: default
; eval (selection): #rtrace (map inc (rang...
; (err) Execution error (WebsocketNotConnectedException) at org.java_websocket.WebSocketImpl/send (WebSocketImpl.java:673).
; (err) null
```

**Comment by jpmonettas** [comment]
@FongHou maybe if you can jump into clojurians slack #flow-storm channel we can troubleshoot it more dynamically.

**Comment by jpmonettas** [comment]
@FongHou This commit c7af52464cb70a04582f175d644435ca7cca95db includes two new keywords you can use `:debugger-host` and `:runtime-host`.

**Comment by jpmonettas** [comment]
Released on `3.0.197`

**Comment by FongHou** [comment]
Sorry I went offline for a while. 

I tried 3.0.197, but no luck. I can see two things. First, on debugger side I can see websocket is always bound to 0.0.0.0 as shown in netstat -na, regardless what :debugger-host arg is. Second, on remote nrepl server side, as soon as debugger connects to nrepl, it's the nrepl server initiating a reversed connection back to debugger always using localhost and default port 7722. It seems debugger client should "send" the debugger-host (if local? is false) to nrepl server "telling" it what host address to connect back to debugger's websocket.

Does this logic make sense?

```
PS C:\Users\houfe> netstat -na

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:7722           0.0.0.0:0              LISTENING
```

**Comment by jpmonettas** [comment]
Damn it, sorry I tried with local ips on my box and thought it was working, my bad. I just fixed the bug and pushed it to master just in case you want to give it a shot, but haven't tested since I need to leave now. I'll test it tomorrow morning and comment here.

**Comment by jpmonettas** [comment]
Just tried it on the latest version `3.0.198` and everything seems to be working fine.

My test :

On a windows box (192.168.1.103) started a clojure nrepl like : 
```
clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version "1.0.0"} com.github.jpmonettas/flow-storm-inst {:mvn/version "3.0.198"}}}' -M -m nrepl.cmdline -b "192.168.1.103" -p 9000
```

And connected from my linux box (192.168.1.8) like : 
```
clj -Sdeps '{:deps {com.github.jpmonettas/flow-storm-dbg {:mvn/version "3.0.198"}}}' -X flow-storm.debugger.main/start-debugger :port 9000 :debugger-host '"192.168.1.8"' :runtime-host '"192.168.1.103"'
```

Everything worked fine, also connected a repl client from my linux and played around tracing stuff, everything looks fine.

**Comment by FongHou** [comment]
Thanks @jpmonettas!
