### ISSUE TITLE
syntax error on import

### ISSUE THREAD

**Issue by tommy-mor** [jpmonettas/flow-storm-debugger#49]
```
 [{:type clojure.lang.Compiler$CompilerException
   :message Syntax error compiling at (flow_storm/runtime/indexes/api.cljc:179:21).
   :data #:clojure.error{:phase :compile-syntax-check, :line 179, :column 21, :source flow_storm/runtime/indexes/api.cljc}
   :at [clojure.lang.Compiler analyze Compiler.java 6808]}
  {:type java.lang.RuntimeException
   :message No such var: async/to-chan!
   :at [clojure.lang.Util runtimeException Util.java 221]}]
 :trace ...

```
seems like async/to-chan is a thing, but not to-chan!

https://clojuredocs.org/clojure.core.async/to-chan

im using clojure 1.11.1, but also happens on clojure 1.10.1...

I feel like im missing something...

**Comment by tommy-mor** [comment]
https://github.com/clojure/core.async/blob/6ac8ed2a26c67bbc3cc43e4e650f97c984666b0c/src/main/clojure/cljs/core/async.cljs#L406

now I see that it does exist... not sure what is going on

**Comment by tommy-mor** [comment]
I am using leiningen not deps, maybe thats the problem. I just imported the two artifacts from maven though, so it should work.

**Comment by jpmonettas** [comment]
Hmm looks like a core.async version mismatch. 

What command are you running to start your repl? 

Does running `clj -Sforce -Sdeps '{:deps {com.github.jpmonettas/flow-storm-dbg {:mvn/version "RELEASE"} com.github.jpmonettas/flow-storm-inst {:mvn/version "RELEASE"}}}'` on a empty folder works?

If it doesn't, can you paste the output of : 

 `clj -Sforce -Sdeps '{:deps {com.github.jpmonettas/flow-storm-dbg {:mvn/version "RELEASE"} com.github.jpmonettas/flow-storm-inst {:mvn/version "RELEASE"}}}' -S tree`

so I can check the dependencies.

**Comment by jpmonettas** [comment]
> I am using leiningen not deps, maybe thats the problem. I just imported the two artifacts from maven though, so it should work.

oh, if you are using leiningen, can you run a `lein deps :tree` on your app folder?

**Comment by tommy-mor** [comment]
https://pastebin.com/3JCMpf6Q this is my deps tree. trying to read this, im a but confused by this.

**Comment by tommy-mor** [comment]
https://pastebin.com/qQ9EaFzP this has the full "confusing dependencies" section... got cut off on other paste

**Comment by tommy-mor** [comment]
i loaded into empty project and it worked, going to try to reproduce it

**Comment by jpmonettas** [comment]
Hey that would be great. It is some dependency causing issues there. I wasn't able to figure it out by just looking at the deps tree

**Comment by tommy-mor** [comment]
turned out to be an issue with lieningen's :aot system keeping a different version of core.async on the classpath... very confusing

**Comment by jpmonettas** [comment]
@tommy-mor Damn, that is confusing. Glad to know you where able to figure it out.
