### ISSUE TITLE
Add keyboard support 

### ISSUE THREAD

**Issue by jpmonettas** [jpmonettas/flow-storm-debugger#5]
It would be nice to move around the debugger by using the keyboard

**Comment by jpmonettas** [comment]
There is basic keyboard support, but the only implemented commands so far are :

- x Close current flow, when in the flow tab
- X Close all flows          "
- x Close current Ref, when in the refs tab
- X Close all Refs,         "

Will keep adding more commands

**Comment by Liverm0r** [comment]
I am a vim user and I would like to have vim-like style for keys: hjkl — as arrows.

But I guess something more general would be to support:
- changing focus between areas with tab/shift+tab;
- changing focus inside area with arrow kes.
- enter to select, esc to unselect.

**Comment by jpmonettas** [comment]
Keyboard support was added in version 3.6.
The current bindings are https://jpmonettas.github.io/flow-storm-debugger/user_guide.html#_key_bindings and not currently customizable.

I'm closing this one since there is this other issue for tracking key bindings customization https://github.com/jpmonettas/flow-storm-debugger/issues/83
