### ISSUE TITLE
macOS: Debugger GUI window go to background and no way to switch to it

### ISSUE THREAD

**Issue by lucywang000** [jpmonettas/flow-storm-debugger#52]
(Thanks for this amazing project!)

On mac os Monterey (12.3), after `(fs-api/local-connect)`, the GUI would pop up, but would go to the background immediately after it loses the focus, and can't be switched to by Alt+Tab etc.

The only way to get it back is to go to locate it in the grid of all windows with the "three fingers swipe upwards" gesture or "Ctrl+Up" hot key.

**Comment by jpmonettas** [comment]
Hi @lucywang000!

Unfortunately I don't have a mac to test, but looks to me that because your editor and the debugger are two windows of the same app you can't use Alt+Tab, since that is for switching between apps.

It looks like there is Command+` for switching between windows of the same app in mac os. Have you tried that?

**Comment by lucywang000** [comment]
Hey @jpmonettas , thanks for your reply!

> It looks like there is Command+` for switching between windows of the same app in mac os. Have you tried that?

Yeah I tried that before posting here - do not work either :(

I tried to launch the debugger from both my editor (emacs) and from the lein repl in the terminal. In both cases I can't find this debugger UI in normal ways.

**Comment by jpmonettas** [comment]
Interesting, I wonder what can be causing it, since it is just a normal java-fx window.

**Comment by lucywang000** [comment]
With some searching on the web, here is a fix: https://github.com/jpmonettas/flow-storm-debugger/pull/53

**Comment by jpmonettas** [comment]
Thanks @lucywang000 !
