### ISSUE TITLE
Value inspector breadcrumbs on large values aren't helpful

### ISSUE THREAD

**Issue by Cyrik** [jpmonettas/flow-storm-debugger#57]
I usually use the value inspector in pretty big maps, so I navigate into them. It would be great if the breadcrumbs didn't try to show the whole value (which is too big anyway) but instead showed the navigation needed to get to the current display, i.e. [:a 1 :body 5] or similar. Even better if this navigation could be copied out.

**Comment by jpmonettas** [comment]
Make sense, I will experiment with that when I get some time. Thanks!

**Comment by jpmonettas** [comment]
@Cyrik The latest release `3.2.271` contains the inspector following your idea. I haven't add a navigation copy button since I can't think of a use case given we have the def button to bring any value to the repl.

Do you have a use case for it?

**Comment by Cyrik** [comment]
Thanks for getting these done so quick!
I know I sometimes use that button in portal when I'm deeply navigated into something, but portal doesn't have the def, so you probably don't need it here. I'll open a new issue if I notice that it's missing for something.
