### ISSUE TITLE
Unable to launch debugger again after closing it

### ISSUE THREAD

**Issue by matt-y** [jpmonettas/flow-storm-debugger#63]
[I was able to launch the debugger after following the quickstart instructions for clojure here](https://jpmonettas.github.io/flow-storm-debugger/user_guide.html#_clojure). 

After launching the debugger with `(fs-api/local-connect)` then closing the window, running `(fs-api/local-connect)` a second time results in `nil` at the REPL and no debugger GUI being launched. 

In order to launch the debugger again, it seems I am required to either do the following:
1. restart my repl, and perform the quickstart steps again, or 
2. run ` (fs-api/stop)` after closing the GUI window, and then run `(fs-api/local-connect)` again to launch the GUI a second time. 

I am finding this to be very confusing UX. My expectation is that running `local-connect` a second time would just launch the debugger again - or I suppose connect to whatever debugger exists in the background. Minimally this needs to be spelled out explicitly in documentation.

**Comment by jpmonettas** [comment]
Thanks for your comment, I'll try to improve the UX. 

The current way of using it is to start it by calling fs-api/local-connect and stop it (closing the window) by calling fs-api/stop. So calling stop will do everything, no need to close the windows first.

Normally I never call those by typing them, I assign a key bindings on my editor to show the debugger and hide it. If you are using emacs you can use the integration here https://github.com/jpmonettas/flow-storm-debugger/tree/master/editors, other editors integration will come in the future.

**Comment by matt-y** [comment]
Oh fantastic - I totally missed there was an emacs integration. Thanks. 

I would say this issue could be marked as closed unless you'd like to use it to track some UX change around the above experience.

**Comment by jpmonettas** [comment]
Nice, I'll close it for now then. Take a look at this video where I demo my workflow with the debugger if you are interested in how I use it https://youtu.be/2nH59edD5Uo
