### ISSUE TITLE
UX: GUI icon hover state changes the background to white making the icon unreadable

### ISSUE THREAD

**Issue by matt-y** [jpmonettas/flow-storm-debugger#65]
I noticed within the code stepping interface that the icons for stepping through the traces when moused over seem to go all-white making them illegible. Icons in the Toolbar and elsewhere also seem to have this same issue. 

I would expect the color of the icon or text within a button should also be changing when hovered over to keep the icon/text visible. 

This was in the "light" color scheme.

**Comment by jpmonettas** [comment]
Thanks for reporting it, that is a bug so will be fixed soon.
