### ISSUE TITLE
UX: Add a unique identifier for each Flowstorm window

### ISSUE THREAD

**Issue by zikajk** [jpmonettas/flow-storm-debugger#68]
I often debug CLJ and CLJS at the same time. That's why I open Flowstorm twice. 

Would it be possible to visually distinguish the windows in some way (if it is not possible to use one window for both environments)?
![Screenshot 2023-01-05 at 11 32 09](https://user-images.githubusercontent.com/40757859/210759619-12891b62-1bdf-47e5-968a-3243ecd6b0ba.png)

On Macos, multiple Flowstorm windows hide under one icon in Dock, so it is not entirely clear what one wants to minimize or maximize but I am not sure if this is related or if that is javafx problem :-)
![Screenshot 2023-01-05 at 11 32 55](https://user-images.githubusercontent.com/40757859/210759804-c32b0736-1465-4865-9105-ccab5296b02e.png)

**Comment by jpmonettas** [comment]
So to distinguish them visually when they are open you can use the :styles key when starting the debugger, and assign
like a different background or tab color using java-fx css styles like : 

```
clj -Sforce -Sdeps '{:deps {com.github.jpmonettas/flow-storm-dbg {:mvn/version "RELEASE"}}}' -X flow-storm.debugger.main/start-debugger :port 35555 :styles '"magenta-debugger.css"'
```

being that magenta-gebugger.css : 

```
.vertical-tab:selected {
        -fx-background-color: #971ba3;
}
```

you can see all the styles here : https://github.com/jpmonettas/flow-storm-debugger/blob/master/resources/styles.css

I'm not using macosx so not sure how to customize the doc, but we should be able to customize anything that can be customized with a java application, for example we can change the window title by changing this : 

https://github.com/jpmonettas/flow-storm-debugger/blob/master/src-dbg/flow_storm/debugger/ui/main.clj#L209

The config you see there as a parameter contains keys passed on the command line, so maybe we can add `:title` ?

If you try it and it works for you and macosx experience I have no problem merging that into master, so let me know!

**Comment by zikajk** [comment]
Thanks
- themes work great!
- I try it. If adding a title helps and the title is displayed in the title of a window itself, it would probably solve the problem of how to distinguish individual debuggers.

**Comment by jpmonettas** [comment]
You can now specify a title to distinguish between multiple debugger instances https://jpmonettas.github.io/flow-storm-debugger/user_guide.html#_styling_and_theming
