### ISSUE TITLE
unknown-error with `instrument recursively` while using potemkin's `import-vars`

### ISSUE THREAD

**Issue by ikappaki** [jpmonettas/flow-storm-debugger#71]
Hi,

there appears to be a corner case issue when using UI's `instrument recursively` and [potenmkin](https://github.com/clj-commons/potemkin)'s `import-vars` fn:

```
Error re-evaluating middle/one {:type :unknown-error, :msg "Syntax error compiling at (0:0).", :original-form (defn one [] (two))}
```

`import-var` is a helper function to (quoting from the readme file):

> import-vars allows functions, macros, and values to be defined in one namespace, and exposed in another.

To reproduce, we are going to create a fn `one` calling fn `two` in ns `back`; the `one` fn will be exposed in ns `middle` using `import-vars` and will be called by fn `top` in ns `front`  as `middle\one`. Finally, the `front` ns will be `require`'d from the `issue` namespace.

1. Create a `deps.edn` with flow storm and potemkin deps:
``` clojure
{:paths ["src"]

 :deps {com.github.jpmonettas/flow-storm-dbg {:mvn/version "3.3.309"}
        potemkin/potemkin {:mvn/version "0.4.6"}}}
```
2. create the `src/issue.clj`, `src/front.clj`, `src/middle.clj` and `src/back.clj` files as described earlier
``` clojure
(ns issue
  (:require front))

(comment
  (front/top)
  ;;
  )
```
``` clj
(ns front
  (:require middle))

(defn top []
  (middle/one))
```
``` clj
(ns middle
  (:require back
            potemkin))

(potemkin/import-vars
 [back one])
```
``` clj
(ns back)

(defn two []
  (println :two))

(defn one []
  (two))
```
3. Run the `clojure` cli tool to bring up the repl.
4. Load flow storm
``` clj
(do (require '[flow-storm.api :as fs-api]) (fs-api/local-connect))
```
5. Load `src/issue.clj` 
``` clj
(load-file "src/issue.clj")
```
6. In the flow storm UI, `instrument recursively` the `front/top` fn
![image](https://user-images.githubusercontent.com/34983288/215339359-bb61b797-5c30-4a76-8c62-bf7a22b02bd6.png)
7. You should see the uknown error in the repl
```
Error re-evaluating middle/one {:type :unknown-error, :msg "Syntax error compiling at (0:0).", :original-form (defn one [] (two))}
```

Evaluating `(front/top)` from ns `issue` otherwise prints out `:two` as expected.

I suspect the issue here is that flow storm tries to locate fn `two` in ns `middle`, but it is only fn `one` that was imported in that ns.

REPL output
```
Clojure 1.11.1
user=> (do (require '[flow-storm.api :as fs-api]) (fs-api/local-connect))
[Starting Events queue subsystem]
Events queue started
[Starting Runtime Api subsystem]
[Starting docs subsystem]
Loading docs using () files
[Starting UI subsystem]
Jan 29, 2023 com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @16ae5d46'
#object[flow_storm.runtime.taps$setup_tap_BANG_$tap_f__10647 0x57ba286d "flow_storm.runtime.taps$setup_tap_BANG_$tap_f__10647@57ba286d"]
user=> (load-file "src/issue.clj")
nil
user=> Instrumenting var front/top {:deep? true}
Re-evaluating var: front/top deep?: true instrument?: true
Re-evaluating var: middle/one deep?: true instrument?: true
Error re-evaluating middle/one {:type :unknown-error, :msg "Syntax error compiling at (0:0).", :original-form (defn one [] (two))}
```

Thanks

**Comment by jpmonettas** [comment]
Thanks for the detail report!

Hmm, interesting, I'll take a look.

**Comment by jpmonettas** [comment]
Fixed in Hansel https://github.com/jpmonettas/hansel/commit/8bc7d761b658d1f36b3f4cf74942364b53d30a99

FlowStorm master is currently using Hansel 0.1.42 which contains the fixes
