### ISSUE TITLE
Where install section guide

### ISSUE THREAD

**Issue by overtube** [jpmonettas/flow-storm-debugger#77]
I was not find where and how I can install these

**Comment by overtube** [comment]
Please help

**Comment by jpmonettas** [comment]
Hi! 

The user guide is here https://jpmonettas.github.io/flow-storm-debugger/user_guide.html
There is a quickstart section for Clojure and another for ClojureScript.

If you have any issues please add them here or show up in #flow-storm in Clojurians slack.

Cheers!

**Comment by overtube** [comment]
Thanks!
