### ISSUE TITLE
Deref of promise blocks code evaluating

### ISSUE THREAD

**Issue by Gorovoi** [jpmonettas/flow-storm-debugger#78]
Example:
```
#trace
(defn blocks []
  (promise)
  1)

(blocks)
```
Debugger will try deref promise to print it, and because of that it will be blocked forever.

Possible solution is check if value is IBlockingDeref, and deref it with timeout.
Example: 
```
(utils/derefable? x)
 {:ref/snapshot (if (instance? clojure.lang.IBlockingDeref x) (deref x 0 x) (deref x))
  :ref/type (type x)}
```

**Comment by jpmonettas** [comment]
Good catch @Gorovoi and thanks for the solution!

Do you want to make a PR?
Otherwise I'll add it soon.

**Comment by jpmonettas** [comment]
Maybe instead of x as the default value we can use :ref/timeout as the :ref/snapshot value? so it is easy to see what happened there
