### ISSUE TITLE
Cannot invoke "clojure.storm.IForm.getForm()" because "form" is null

### ISSUE THREAD

**Issue by htenes** [jpmonettas/flow-storm-debugger#81]
(defproject trader "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [
                 ]
  :profiles {:dev {:dependencies [[com.github.jpmonettas/clojure "RELEASE"]
                                  [com.github.jpmonettas/flow-storm-dbg "RELEASE"] ]
                   :exclusions [org.clojure/clojure] ;; for disabling the official compiler
                   :jvm-opts ["-Dclojure.storm.traceEnable=true"
                              "-Dclojure.storm.instrumentEnable=true"
                              "-Dclojure.storm.instrumentOnlyPrefixes=trader.,"]}}
  )

here is my project.clj
When I open the repel and connect to the flow gui eveeryting is fine.
But after evaluating
#rtrace
    (reduce + (map inc (range 10)))
I get 
Execution error (NullPointerException) at clojure.storm.FormRegistry/makeFormMap (FormRegistry.java:25).
Cannot invoke "clojure.storm.IForm.getForm()" because "form" is null

Any idea what am I doing wrong?

**Comment by htenes** [comment]
I figured it out. The documentation is confusing as hell... basicaly you have this commands to work with when using ClojureStorm

**Comment by jpmonettas** [comment]
@htenes yeah I have a TODO on my list to improve that aspect of the docs and to add a warning message when trying to use #trace and #rtrace with ClojureStorm
