### ISSUE TITLE
Add a keyboard customization system

### ISSUE THREAD

**Issue by jpmonettas** [jpmonettas/flow-storm-debugger#83]
There is currently support for keyboard with keybindings described here https://jpmonettas.github.io/flow-storm-debugger/user_guide.html#_key_bindings, but making them configurable would be a nice enhancement.

A previous step is to develop some kind of config file, where custom keybindings can be specified.

**Comment by agzam** [comment]
A somewhat related question here: do you think it would be possible, or perhaps it's already possible (sorry, I'm very new to this project, so I don't know), to have it running in "server mode," where the UI can be controlled directly from the editor? It would be nice to be able to step through things without leaving Emacs/Vim/etc.

**Comment by jpmonettas** [comment]
@agzam yes! it is currently possible, look at https://github.com/jpmonettas/cider-storm/ 
I only implemented it for Emacs since it is what I use, but FlowStorm has a nRepl middleware exposing all the stepping functionality, so any editor/ide should be able to do the same.

Let me know if you need help with any of that.

**Comment by agzam** [comment]
Why though does'n it let me use cider-storm? `cider-storm-debug-current-fn` complains `No recordings found for my-project/my-ns`

**Comment by jpmonettas** [comment]
What is your current setup? Do you have recordings when running cider-storm-debug-current-fn? can you see them with the normal FlowStorm UI?

Please show up in Clojurians slack #flow-storm chan if you want a more dynamic troubleshooting!

**Comment by agzam** [comment]
https://clojurians.slack.com/archives/C03KZ3XT0CF/p1696560383345659
