### ISSUE TITLE
null pointer execeptions appears as empty error

### ISSUE THREAD

**Issue by slifin** [jpmonettas/flow-storm-debugger#9]
They're visible in the REPL 
as `Execution error (NullPointerException) at slifin.hello-world/eval21005$fn (form-init135586049465860259.clj:1).
null`

But displayed like this in the UI: 
<img width="543" alt="Screenshot 2020-10-31 at 13 28 05" src="https://user-images.githubusercontent.com/198857/97780488-e9f56400-1b7c-11eb-90b5-d83a385a2788.png">

Testing with `#ztrace (inc nil)`

**Comment by jpmonettas** [comment]
Thanks for reporting @slifin, this is fixed in version 0.3.1 of flow-storm (the tracing library). There is also a new version of the debugger (0.3.2) which fixes some details.

Cheers!
