### ISSUE TITLE
The ClojureStorm clojure compiler doesn't work when Ring Gzip middleware is required

### ISSUE THREAD

**Issue by crimsonhawk47** [jpmonettas/flow-storm-debugger#90]
This an odd one I had to track down, but when requiring `[ring.middleware.gzip]`, it won't let me use your Clojure compiler for some reason. It crashes silently with no error, even if we're just running with `clj`. ]

This is with the latest of ClojureStorm and `amalloy/ring-gzip-middleware {:mvn/version "0.1.4"}`

**Comment by crimsonhawk47** [comment]
Narrowed further, it seems to be something funky going on in `gzip.clj` where they are doing a defmethod

```clj
; exactly the same as do-copy for [InputStream OutputStream], but
; flushes the output on every chunk; this allows gzipped content to start
; flowing to clients ASAP (a reasonable change to ring IMO)
(defmethod @#'io/do-copy [(class (piped-gzipped-input-stream*)) OutputStream]
  [^InputStream input ^OutputStream output opts]
  (let [buffer (make-array Byte/TYPE (or (:buffer-size opts) 1024))]
    (loop []
      (let [size (.read input buffer)]
        (when (pos? size)
          (do (.write output buffer 0 size)
              (.flush output)
              (recur)))))))
```

**Comment by jpmonettas** [comment]
Oh nice catch and thanks for narrowing that down @crimsonhawk47.

The tracing system was only expecting symbols after the defmethod keyword, I didn't know you can write a defmethod like that.

In any case it is fixed now in : 
- `[com.github.jpmonettas/clojure "1.12.0-alpha4_2"]`
- `[com.github.jpmonettas/clojure "1.11.1-8"]`

Thanks again!
