### ISSUE TITLE
:preload - flow-storm.api => ClassNotFoundException - clojure.core.reducers.CollFold

### ISSUE THREAD

**Issue by agigao** [jpmonettas/flow-storm-debugger#95]
Hi Juan,

First of all, thanks for stepping in enhancing developer experience in Clojure ecosystem.

Now, my first attempt to debug cljs using flow-storm failed miserably, adding `flow-storm.api` to `:preloads` throws `ClassNotFoundException - clojure.core.reducers.CollFold`.

Would you please provide any pointers how to deal with it?

Thanks,
Giga

**Comment by jpmonettas** [comment]
Hi @agigao, thanks! 
That error looks to me like something is bringing in Clojure < 1.11 which isn't supported by the AOT compiled artifact.

Try using Clojure 1.11. 

If you can't or that doesn't seems to fix the error please let me know, and we can debug it further.
Also show up in Clojurians #flow-storm chan if you want to troubleshoot it a little more interactive.

**Comment by jpmonettas** [comment]
@agigao were you able to figure out and solve the issue?

**Comment by jpmonettas** [comment]
Closing this for now, please reopen if you are still seeing it
