### ISSUE TITLE
Please also distribute a sources artifact along `com.github.jpmonettas/clojure`

### ISSUE THREAD

**Issue by vemv** [jpmonettas/flow-storm-debugger#96]
Hi!

It would be best practice (and much practical, for a complete IDE experience) that the `com.github.jpmonettas/clojure` artifact had a `"sources"` companion.

e.g. I should be able to depend on `[com.github.jpmonettas/clojure "1.11.1-9" :classifier "sources"]`, and I should get the .java sources for the Clojure compiler/runtime.

Thanks - V

**Comment by jpmonettas** [comment]
hi @vemv!
Oh sure, thanks for remembering me that. Do you know if there is a way of uploading the sources jar after? or I need to publish a different version with both like :
```
mvn deploy:deploy-file -Dfile=target/clojure-1.11.1.-9.jar -Dsources=target/clojure-1.11.1.-9-sources.jar -DrepositoryId=clojars -DpomFile=pom.xml -Durl=https://clojars.org/repo
```
I tried deploy-file with only jar sources but it needs a project jar file also. If it isn't possible I can release the next version and include sources there.

**Comment by vemv** [comment]
Thanks, @jpmonettas !

>  If it isn't possible I can release the next version and include sources there.

Sounds good to me - it's not an urgent issue at all.

`mvn deploy:deploy-file -Dfile=target/clojure-1.11.1.-9.jar -Dsources=target/clojure-1.11.1.-9-sources.jar` looks like a correct invocation to me.

(Just in case: including the sources in the regular .jar would be dangerous)

**Comment by jpmonettas** [comment]
Since ClojureStorm is a fork of Clojure with some patches I'm running the same commands as Clojure itself to package, which generate the jars for the classes and the sources separately. I just forgot to include the sources in the deploy-file plugin when deploying.
I fixed the deploy script so expect the next release to be uploaded with the sources!

Thanks again!

**Comment by vemv** [comment]
Cheers 🍻
